import { Activity, Check, Database, Eye, KeyRound, RefreshCw, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { skills } from '@/lib/mock-data';

export function SupabaseSetup() {
  const [mode, setMode] = useState('Custom Supabase'); const [url, setUrl] = useState(''); const [anon, setAnon] = useState(''); const [role, setRole] = useState(''); const [visible, setVisible] = useState(false); const [status, setStatus] = useState('Not tested'); const [connected, setConnected] = useState(false);
  function test() { if (mode === 'Custom Supabase') { try { const parsed = new URL(url); if (parsed.protocol !== 'https:' || !anon || !role) { setStatus('Enter an HTTPS project URL and both demo keys.'); return; } } catch { setStatus('Enter a valid HTTPS project URL.'); return; } } setStatus('Demo connection passed'); setConnected(true); setRole(''); setAnon(''); }
  return <div className="expanded-page"><div className="connector-hero"><span className="connector-icon"><Database size={22}/></span><div><h3>Supabase</h3><p>Postgres · Auth · Storage · Functions</p></div><Button variant="outline" size="sm" onClick={() => { setConnected(false); setStatus('Disconnected'); }}>Disconnect</Button></div><div className="feature-tabs">{['Lovable Cloud', 'Custom Supabase'].map(item => <Button key={item} size="sm" variant={mode === item ? 'editorActive' : 'ghost'} onClick={() => { setMode(item); setConnected(false); setStatus('Not tested'); }}>{item}</Button>)}</div><div className="local-notice">Simulation only — use sample keys. No credentials are saved and no provider is contacted.</div>{mode === 'Custom Supabase' ? <div className="setup-form"><label className="settings-field">Project URL<input value={url} onChange={e => setUrl(e.target.value)} placeholder="https://xyzcompany.supabase.co"/></label><label className="settings-field">Anon public key<input type="password" autoComplete="off" value={anon} onChange={e => setAnon(e.target.value)} placeholder="Sample public key"/></label><label className="settings-field">Service role key<div className="secret-input"><input type={visible ? 'text' : 'password'} autoComplete="off" value={role} onChange={e => setRole(e.target.value)} placeholder="Sample private key"/><Button variant="ghost" size="icon-sm" aria-label="Toggle service key visibility" onClick={() => setVisible(!visible)}><Eye size={13}/></Button></div></label></div> : <div className="managed-resources"><Database size={28}/><h3>Managed project</h3><p>Database, users, storage, and functions</p></div>}<div className="context-actions"><Button variant="editorActive" size="sm" onClick={test}><Check size={13}/>Test connection</Button><span role="status" className={connected ? 'status-good' : 'status-muted'}>{status}</span></div>{connected && <div className="schema-state"><b>Demo schema</b><span>auth.users</span><span>public.tables</span><Button variant="outline" size="sm" onClick={() => setStatus('Demo schema synchronized just now')}><RefreshCw size={13}/>Sync schema</Button></div>}</div>;
}
export function SkillsManager({ enabled, onChange }: { enabled: string[]; onChange: (items: string[]) => void }) {
  const [editing, setEditing] = useState<string | null>(null); const [prompts, setPrompts] = useState<Record<string, string>>({}); const [draftActive, setDraftActive] = useState(false); const [notice, setNotice] = useState('');
  return <div className="expanded-page"><h3>Active skills</h3><div className="skills-grid">{skills.map((skill, index) => <article className="skill-card" key={skill.command}><header><b>{skill.title}</b><span>{index % 2 ? 'Project' : 'Workspace'}</span></header><code>{skill.command}</code><p>{skill.detail}</p><div className="context-actions"><Button role="switch" aria-checked={enabled.includes(skill.command)} aria-label={`Enable ${skill.title}`} variant={enabled.includes(skill.command) ? 'editorActive' : 'outline'} size="sm" onClick={() => onChange(enabled.includes(skill.command) ? enabled.filter(item => item !== skill.command) : [...enabled, skill.command])}>{enabled.includes(skill.command) ? 'Active' : 'Disabled'}</Button><Button size="sm" variant="ghost" onClick={() => setEditing(editing === skill.command ? null : skill.command)}>Edit prompt</Button></div>{editing === skill.command && <label className="settings-field">Instructions<textarea value={prompts[skill.command] ?? skill.detail} onChange={e => setPrompts({ ...prompts, [skill.command]: e.target.value })}/><Button variant="outline" size="sm" onClick={() => { setEditing(null); setNotice('Skill instructions saved for this session.'); }}>Save prompt</Button></label>}</article>)}</div><h3>Draft skills</h3><article className="skill-card"><header><b>Release review</b><span>Project · Draft</span></header><p>Review the release checklist before publication.</p><Button variant="outline" size="sm" onClick={() => { setDraftActive(!draftActive); setNotice(draftActive ? 'Release review returned to drafts.' : 'Draft marked active in this demo.'); }}>{draftActive ? 'Return to draft' : 'Activate draft'}</Button></article><p role="status" className="local-notice">{notice || 'Demo skill library · changes apply to this session only.'}</p></div>;
}
export function SeoSurface() {
  const [title, setTitle] = useState('Orbit — Money made clear'); const [description, setDescription] = useState('A calm place for spending, saving, and everything ahead.'); const [image, setImage] = useState(''); const [card, setCard] = useState('summary_large_image'); const [indexing, setIndexing] = useState(true); const [llms, setLlms] = useState(false); const [preview, setPreview] = useState(false); const [notice, setNotice] = useState('');
  return <div className="expanded-page"><div className="seo-previews"><div className="search-preview"><small>GOOGLE SEARCH · orbit-finance.lovable.app</small><b>{title}</b><p>{description}</p></div><div className="social-preview"><div className="social-cover">ORBIT</div><small>SOCIAL PREVIEW · {card}</small><b>{title}</b><p>{description}</p></div></div><h3>Metadata</h3><label className="settings-field">Page title<input value={title} onChange={e => setTitle(e.target.value)}/></label><label className="settings-field">Meta description<textarea value={description} onChange={e => setDescription(e.target.value)}/></label><label className="settings-field">OG image URL<input type="url" value={image} onChange={e => setImage(e.target.value)} placeholder="https://example.com/cover.jpg"/></label><label className="settings-field">Twitter card type<select value={card} onChange={e => setCard(e.target.value)}><option>summary_large_image</option><option>summary</option></select></label><Toggle label="Allow AI search indexing" value={indexing} onChange={setIndexing}/><Toggle label="Generate llms.txt" value={llms} onChange={setLlms}/><div className="context-actions"><Button variant="outline" size="sm" disabled={!llms} onClick={() => setPreview(!preview)}>Preview llms.txt</Button><Button variant="editorActive" size="sm" onClick={() => setNotice(`Demo audit: ${title ? 'title present' : 'title missing'} · ${description ? 'description present' : 'description missing'} · ${image ? 'cover URL set' : 'cover URL missing'}`)}>Audit SEO with AI</Button><Button variant="outline" size="sm" onClick={() => setNotice('Metadata saved in this session only.')}>Save metadata</Button></div>{preview && llms && <pre className="terminal-output">{`# ${title}\n\n${description}\n\n## Pages\n- /: Overview\n- /dashboard: Weekly insights`}</pre>}<p className="local-notice" role="status">{notice || 'Preview settings only. Published metadata and crawler access are unchanged.'}</p></div>;
}
export function AiSurface() {
  const [instructions, setInstructions] = useState('Preserve the compact editor. Use typed local state and accessible controls. Keep credentials out of client code.'); const [notice, setNotice] = useState('');
  return <div className="expanded-page"><h3>Model routing</h3><div className="routing-row"><Activity size={19}/><div><b>Lovable AI Gateway</b><small>No live model connected · frontend simulation</small></div><span className="connector-live">Demo</span></div><div className="metrics-row">{[['Tokens processed', '248k'], ['Prompt cache hits', '84%'], ['Response latency', '1.1s']].map(([label, value]) => <article key={label}><small>{label}</small><b>{value}</b><em>Sample metric</em></article>)}</div><details open><summary>System prompt & agent instructions</summary><label className="settings-field">Project steering<textarea value={instructions} onChange={e => setInstructions(e.target.value)}/></label><Button variant="editorActive" size="sm" onClick={() => setNotice('Instructions saved for this session.')}>Save instructions</Button></details><p className="local-notice" role="status">{notice || 'No AI requests are made.'}</p></div>;
}
export function SecurityAudit() {
  const [scanned, setScanned] = useState(false); const [csp, setCsp] = useState(false); const [origins, setOrigins] = useState("'self'"); const [notice, setNotice] = useState('');
  return <div className="expanded-page"><div className="audit-status"><ShieldCheck size={25}/><div><b>{scanned ? 'Demo review complete' : 'Security review'}</b><small>No real audit has been performed</small></div><Button variant="editorActive" size="sm" onClick={() => { setScanned(true); setNotice('Sample findings refreshed. This is not a security guarantee.'); }}>Run security scan</Button></div><div className="audit-table">{[['Row Level Security', '4 sample tables with RLS policies'], ['Authentication rules', 'Demo server-only credential boundary'], ['Content Security Policy', 'Review allowed external origins'], ['Dependency audit', 'Sample dependency report']].map(([label, detail]) => <div key={label}><ShieldCheck size={15}/><span><b>{label}</b><small>{detail}</small></span>{label === 'Content Security Policy' ? <Button variant="outline" size="sm" onClick={() => setCsp(!csp)}>Configure</Button> : <span className="status-muted">{scanned ? 'Demo pass' : 'Not verified'}</span>}</div>)}</div>{csp && <label className="settings-field">Allowed origins<textarea value={origins} onChange={e => setOrigins(e.target.value)}/><Button variant="outline" size="sm" onClick={() => { setCsp(false); setNotice('Demo CSP saved. Site headers are unchanged.'); }}>Save CSP</Button></label>}<p role="status" className="local-notice">{notice || 'Simulation only — review actual policies before publishing.'}</p></div>;
}
export function AnalyticsExpanded() {
  const [range, setRange] = useState('7 days'); const [selected, setSelected] = useState<number | null>(null); const values = range === '7 days' ? [38, 52, 44, 68, 58, 81, 92] : [63, 76, 49, 82, 66, 95, 72];
  return <div className="expanded-page"><div className="analytics-range"><span>Sample visitor data</span><select aria-label="Analytics date range" value={range} onChange={e => setRange(e.target.value)}><option>7 days</option><option>30 days</option></select></div><div className="metrics-row">{[['Unique visitors', range === '7 days' ? '1,420' : '5,680'], ['Pageviews', range === '7 days' ? '5,890' : '23,560'], ['Avg. session', '2m 45s']].map(([label, value]) => <article key={label}><small>{label}</small><b>{value}</b><em>+14% · demo trend</em></article>)}</div><div className="analytics-card"><b>Visitors</b><div className="bar-chart">{values.map((value, index) => <Button key={index} variant={selected === index ? 'editorActive' : 'primary'} aria-label={`Traffic period ${index + 1}: ${value} visitors`} title={`${value} visitors`} style={{ height: `${value}%` }} onClick={() => setSelected(index)}/>)}</div><p role="status">{selected === null ? `Last ${range}` : `Period ${selected + 1}: ${values[selected]} sample visitors`}</p></div><div className="report-columns">{[['Top referrers', 'Direct', 'Google', 'LinkedIn'], ['Top pages', '/', '/dashboard', '/settings']].map(([title, ...items]) => <section key={title}><h3>{title}</h3>{items.map((item, index) => <div className="referrer-row" key={item}><span>{item}</span><b>{[62, 28, 10][index]}%</b><progress value={[62, 28, 10][index]} max="100"/></div>)}</section>)}</div></div>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="toggle-row"><b>{label}</b><Button role="switch" aria-checked={value} aria-label={label} variant={value ? 'editorActive' : 'outline'} size="sm" onClick={() => onChange(!value)}>{value ? 'On' : 'Off'}</Button></div>; }
export function CloudResources() {
  const [tab, setTab] = useState('Database'); const [resources, setResources] = useState<Record<string, string[]>>({ Database: ['profiles', 'transactions', 'budgets', 'goals'], Users: ['Nathan Hanry', 'Mia Chen', 'Oliver Stone'], Storage: ['public-assets', 'project-files', 'avatars'], Functions: ['sync-github', 'send-invite', 'create-preview'], Secrets: ['VITE_APP_URL', 'GITHUB_TOKEN', 'FIRECRAWL_API_KEY'], Logs: ['Demo build completed', 'Demo preview refreshed', 'Demo Git sync completed'] }); const [selected, setSelected] = useState<string | null>(null); const [create, setCreate] = useState(false); const [name, setName] = useState(''); const [sql, setSql] = useState(false); const [statement, setStatement] = useState('select * from profiles;'); const [notice, setNotice] = useState('');
  return <div className="expanded-page"><div className="feature-kicker"><span className="cloud-status-dot"/>Lovable Cloud <b>Simulated resources</b></div><div className="feature-tabs">{Object.keys(resources).map(item => <Button key={item} variant={tab === item ? 'editorActive' : 'ghost'} size="sm" onClick={() => { setTab(item); setSelected(null); setCreate(false); setSql(false); }}>{item}</Button>)}</div><div className="resource-toolbar"><b>{tab}</b>{tab === 'Database' && <Button variant="outline" size="sm" onClick={() => setSql(!sql)}>Open SQL editor</Button>}<Button variant="editorActive" size="sm" onClick={() => setCreate(!create)}>+ {tab === 'Secrets' ? 'Add secret' : 'New'}</Button></div>{create && <form className="invite-row" onSubmit={e => { e.preventDefault(); setResources({ ...resources, [tab]: [...(resources[tab] ?? []), name] }); setCreate(false); setName(''); setNotice('Demo resource added. No data service was contacted.'); }}><input aria-label="Resource name" required value={name} onChange={e => setName(e.target.value)} placeholder={tab === 'Secrets' ? 'DEMO_SECRET_NAME' : 'Resource name'}/><Button type="submit" variant="outline" size="sm">Add</Button></form>}<div className="resource-list">{resources[tab]?.map((item, index) => <Button key={`${item}-${index}`} variant={selected === item ? 'editorActive' : 'ghost'} onClick={() => setSelected(selected === item ? null : item)}><span>{item}</span><small>{tab === 'Secrets' ? '••••••••' : tab === 'Database' ? `${[4, 28, 3, 2][index] ?? 0} demo rows` : 'Demo resource'}</small></Button>)}</div>{selected && <div className="resource-detail"><h3>{selected}</h3><p>{tab === 'Database' ? 'Columns: id (uuid), created_at (timestamp), name (text)' : tab === 'Secrets' ? 'Masked sample entry. No secret value is stored.' : 'Local sample resource details.'}</p><Button variant="outline" size="sm" onClick={() => setSelected(null)}>Close details</Button></div>}{sql && <label className="settings-field">SQL draft<textarea value={statement} onChange={e => setStatement(e.target.value)}/><Button size="sm" variant="editorActive" onClick={() => setNotice('Demo query complete. No SQL was executed.')}>Run demo query</Button></label>}<p role="status" className="local-notice">{notice || 'All rows and resource states are local demo data.'}</p></div>;
}
