import {
  Activity, ArrowLeft, BarChart3, Check, CheckCircle2, ChevronDown, ChevronRight, Cloud, Code2, Copy,
  CreditCard, Database, Download, ExternalLink, File, FileText, Flame, Folder, Globe2, GitBranch, KeyRound, Lock,
  MoreHorizontal, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, Terminal,
  Users, History as HistoryIcon,
} from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import type { Surface } from "@/lib/mock-data";

const moreNav: { label: string; value: Surface; icon: typeof Cloud }[] = [
  { label: "Analytics", value: "analytics", icon: BarChart3 }, { label: "Cloud", value: "cloud", icon: Cloud },
  { label: "AI", value: "ai", icon: Sparkles }, { label: "Agent integrations", value: "agents", icon: Sparkles },
  { label: "Payments", value: "payments", icon: CreditCard }, { label: "Connectors", value: "connectors", icon: GitBranch },
  { label: "Security", value: "security", icon: ShieldCheck }, { label: "SEO & AI search", value: "seo", icon: Search },
  { label: "Settings", value: "settings", icon: Settings },
];

export function SurfacePanel({ surface, onBack, onSelectSurface }: { surface: Surface; onBack: () => void; onSelectSurface: (surface: Surface) => void }) {
  if (surface === "code") return <CodeSurface/>;
  if (surface === "files") return <FilesSurface/>;
  if (surface === "history") return <HistorySurface onBack={onBack}/>;
  return <MoreSurface surface={surface} onBack={onBack} onSelectSurface={onSelectSurface}/>;
}

function SurfaceTitle({ title, detail, onBack }: { title: string; detail?: string; onBack?: () => void }) {
  return <header className="surface-title">{onBack && <Button variant="ghost" size="icon-sm" onClick={onBack} aria-label="Back to preview"><ArrowLeft size={14}/></Button>}<div><h2>{title}</h2>{detail && <p>{detail}</p>}</div></header>;
}

function CodeSurface() {
  const [selectedFile, setSelectedFile] = useState("src/components/editor/editor.tsx");
  const [query, setQuery] = useState("");
  const [markdownPreview, setMarkdownPreview] = useState(false);
  const files = ["src/components/editor/editor.tsx", "src/components/editor/surfaces.tsx", "src/routes/index.tsx", "src/styles.css", "public/favicon.ico"];
  const visible = files.filter((file) => file.includes(query.toLowerCase()));
  const source = `import { useState } from "react";\nimport { Button } from "@/components/ui/button";\n\nexport function ProjectEditor() {\n  const [surface, setSurface] = useState("preview");\n\n  return (\n    <main className="editor">\n      <ProjectToolbar active={surface} />\n      <Preview surface={surface} />\n    </main>\n  );\n}`;
  return <div className="code-surface"><aside className="code-tree"><div className="code-search"><Search size={13}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search code"/><ChevronDown size={13}/></div><div className="tree-root"><ChevronDown size={13}/><Folder size={14}/><b>project</b></div>{visible.map((file) => <Button variant={selectedFile === file ? "editorActive" : "ghost"} size="sm" className="tree-file" key={file} onClick={() => setSelectedFile(file)}><File size={13}/><span>{file}</span></Button>)}<Button variant="outline" size="sm" className="download-code"><Download size={13}/> Download codebase</Button></aside><main className="code-editor"><div className="code-editor-head"><span>{selectedFile.split("/").at(-1)} <small>TSX</small></span><div><Button variant={selectedFile.endsWith(".md") && markdownPreview ? "editorActive" : "ghost"} size="sm" onClick={() => setMarkdownPreview((value) => !value)}>Preview markdown</Button><Button variant="ghost" size="icon-sm" title="Copy file"><Copy size={13}/></Button><Button variant="ghost" size="icon-sm" title="More"><MoreHorizontal size={13}/></Button></div></div>{markdownPreview ? <div className="markdown-preview"><h2>Project editor notes</h2><p>Readable project documentation can be previewed without leaving the code workspace.</p></div> : <pre className="numbered-code"><code>{source.split("\n").map((line, index) => <span key={`${index}-${line}`}><i>{String(index + 1).padStart(2, "0")}</i>{line || " "}</span>)}</code></pre>}<div className="read-only-note"><Lock size={12}/> Read only <Button variant="editorActive" size="sm">Upgrade</Button></div></main></div>;
}

function FilesSurface() {
  const [query, setQuery] = useState("");
  const files = ["Launch brief.pdf", "Audience research.csv", "Brand direction.md", "Orbit logo.png"];
  return <div className="full-surface"><SurfaceTitle title="Files" detail="Project documents and generated deliverables"/><div className="files-toolbar"><label><Search size={13}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search files"/></label><Button variant="editorActive" size="sm"><Plus size={13}/> Upload file</Button></div><div className="files-grid">{files.filter((file) => file.toLowerCase().includes(query.toLowerCase())).map((file, index) => <article key={file}><span><FileText size={19}/></span><div><b>{file}</b><small>{index % 2 ? "Generated by Lovable" : "Uploaded today"}</small></div><Button variant="ghost" size="icon-sm"><MoreHorizontal size={14}/></Button></article>)}</div></div>;
}

function HistorySurface({ onBack }: { onBack: () => void }) {
  const [tab, setTab] = useState<"History"|"Bookmarks">("History");
  const [selected, setSelected] = useState(0);
  const entries = ["Reworked project editor", "Added preview controls", "Built project dashboard", "Created initial project"];
  return <div className="history-surface"><SurfaceTitle title="History" detail="Browse and restore project versions" onBack={onBack}/><div className="history-tabs"><Button variant={tab === "History" ? "editorActive" : "ghost"} size="sm" onClick={() => setTab("History")}>History</Button><Button variant={tab === "Bookmarks" ? "editorActive" : "ghost"} size="sm" onClick={() => setTab("Bookmarks")}>Bookmarks</Button></div><div className="history-list">{tab === "History" ? entries.map((entry, index) => <button className={selected === index ? "active" : ""} key={entry} onClick={() => setSelected(index)}><span><b>{entry}</b><small>{index === 0 ? "Today, 2:28 PM" : `Sep ${28-index}, 2026`}</small></span>{index === 0 ? <em>Current</em> : <ChevronRight size={13}/>}</button>) : <div className="empty-state"><HistoryIcon size={22}/><b>No bookmarks yet</b><p>Bookmark a version to keep it close.</p></div>}</div>{tab === "History" && selected > 0 && <div className="history-preview-bar"><span>Viewing an earlier version</span><Button variant="outline" size="sm" onClick={() => setSelected(0)}>Back to latest</Button><Button variant="editorActive" size="sm">Restore</Button></div>}</div>;
}

function MoreSurface({ surface, onBack, onSelectSurface }: { surface: Surface; onBack: () => void; onSelectSurface: (surface: Surface) => void }) {
  const safeSurface = moreNav.some((item) => item.value === surface) ? surface : "settings";
  return <div className="more-surface"><aside className="more-sidebar">{moreNav.map(({ label, value, icon: Icon }) => <Button key={value} variant={safeSurface === value ? "editorActive" : "ghost"} size="sm" onClick={() => onSelectSurface(value)}><Icon size={14}/><span>{label}</span></Button>)}</aside><section className="more-content"><SurfaceTitle title={safeSurface === "settings" ? "Project settings" : moreNav.find((item) => item.value === safeSurface)?.label ?? "More"} onBack={onBack}/>{safeSurface === "settings" ? <SettingsSurface/> : safeSurface === "cloud" ? <CloudSurface/> : safeSurface === "analytics" ? <AnalyticsSurface/> : safeSurface === "security" ? <SecuritySurface/> : <FeatureSurface surface={safeSurface}/>}</section></div>;
}

function SettingsSurface() {
  const [tab, setTab] = useState("General");
  const [monitoring, setMonitoring] = useState(true);
  const [livePreview, setLivePreview] = useState(true);
  const [syncing, setSyncing] = useState(false);
  const [lastSync, setLastSync] = useState("Synced 4 minutes ago");
  const syncGit = () => { setSyncing(true); window.setTimeout(() => { setSyncing(false); setLastSync("Synced just now"); }, 650); };
  return <div className="settings-layout"><nav>{["General","Knowledge","Domains","Git"].map((item) => <Button key={item} variant={tab === item ? "editorActive" : "ghost"} size="sm" onClick={() => setTab(item)}>{item}</Button>)}</nav><div className="settings-scroll">{tab === "General" && <><div className="project-identity"><span className="project-symbol">O</span><div><h3>Orbit Finance</h3><p>Owned by Nathan's workspace · Created Sep 5, 2026</p></div></div><SettingsSection title="Project details"><DataRow label="Project name" value="Orbit Finance" action="Edit"/><DataRow label="URL subdomain" value="orbit-finance"/><DataRow label="Owner" value="Nathan Hanry"/><DataRow label="Messages count" value="10"/><DataRow label="AI edits count" value="6"/></SettingsSection><SettingsSection title="Project monitoring"><ToggleRow label="Project monitoring" detail="Regularly checks your project for issues and improvements." value={monitoring} setValue={setMonitoring}/></SettingsSection><SettingsSection title="Preview"><ToggleRow label="Live preview" detail="Show changes while Lovable is building." value={livePreview} setValue={setLivePreview}/></SettingsSection><SettingsSection title="Publishing"><DataRow label="Project category" value="Finance" action="Change"/><ToggleRow label="Visitor analytics" detail="Measure visits to the published app." value={true} setValue={() => undefined}/></SettingsSection></>}{tab === "Knowledge" && <SettingsSection title="Project knowledge"><label className="settings-field">Instructions<textarea defaultValue="Keep the interface calm, clear, and accessible."/></label><Button variant="editorActive" size="sm"><Plus size={13}/> Add knowledge</Button></SettingsSection>}{tab === "Domains" && <SettingsSection title="Domains"><p className="section-description">Connect a custom domain to your published project.</p><label className="settings-field">Domain<input placeholder="app.example.com"/></label><Button variant="editorActive" size="sm">Connect domain</Button></SettingsSection>}{tab === "Git" && <><SettingsSection title="Git"><div className="git-card"><div><Code2 size={17}/><span><b>GitHub repository</b><small>nathan/orbit-finance · main</small></span></div><span className="connection-state"><CheckCircle2 size={13}/> Connected</span></div><div className="git-details"><div><GitBranch size={14}/><span><b>main</b><small>Default branch · Protected</small></span><Button variant="outline" size="sm">Change</Button></div><div><Activity size={14}/><span><b>{lastSync}</b><small>Latest project changes are mirrored automatically.</small></span><Button variant="editorActive" size="sm" onClick={syncGit}>{syncing ? "Syncing…" : "Sync now"}</Button></div></div></SettingsSection><SettingsSection title="Repository actions"><div className="git-actions"><Button variant="outline" size="sm"><ExternalLink size={13}/> Open on GitHub</Button><Button variant="outline" size="sm"><GitBranch size={13}/> Create branch</Button></div></SettingsSection></>}</div></div>;
}

function SettingsSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="settings-section"><h3>{title}</h3><div>{children}</div></section>; }
function DataRow({ label, value, action }: { label: string; value: string; action?: string }) { return <div className="data-row"><span>{label}</span><b>{value}</b>{action ? <Button variant="outline" size="sm">{action}</Button> : <span/>}</div>; }
function ToggleRow({ label, detail, value, setValue }: { label: string; detail: string; value: boolean; setValue: (value: boolean) => void }) { return <div className="toggle-row"><div><b>{label}</b><p>{detail}</p></div><Button variant={value ? "editorActive" : "outline"} size="icon-sm" className={`editor-switch ${value ? "on" : ""}`} onClick={() => setValue(!value)} aria-label={`Toggle ${label}`}><i/></Button></div>; }

function CloudSurface() {
  const [tab, setTab] = useState("Database");
  const resourceIcon = tab === "Database" ? Database : tab === "Logs" ? Activity : tab === "Secrets" ? KeyRound : tab === "Storage" ? Folder : tab === "Functions" ? Terminal : Users;
  const ResourceIcon = resourceIcon;
  const items = tab === "Database" ? ["profiles","transactions","budgets","goals"] : tab === "Users" ? ["Nathan Hanry","Mia Chen","Oliver Stone"] : tab === "Storage" ? ["public-assets","project-files","avatars"] : tab === "Functions" ? ["sync-github","send-invite","create-preview"] : tab === "Secrets" ? ["VITE_APP_URL","GITHUB_TOKEN","FIRECRAWL_API_KEY"] : ["Build completed","Preview refreshed","GitHub sync completed"];
  return <div className="feature-page"><div className="feature-kicker"><span className="cloud-status-dot"/> Lovable Cloud <b>All systems operational</b></div><p className="feature-intro">Your app's data, users, storage, functions, secrets, and logs in one place.</p><div className="feature-tabs">{["Database","Users","Storage","Functions","Secrets","Logs"].map((item) => <Button variant={tab === item ? "editorActive" : "ghost"} size="sm" key={item} onClick={() => setTab(item)}>{item}</Button>)}</div><div className="table-card"><div><ResourceIcon size={18}/><span><b>{tab}</b><small>{tab === "Database" ? "4 tables · healthy" : `${items.length} resources · ready`}</small></span><Button variant="editorActive" size="sm"><Plus size={13}/> New</Button></div>{items.map((item, index) => <p key={item}><span>{item}</span><small>{tab === "Database" ? `${[4,28,3,2][index] ?? 0} rows` : tab === "Logs" ? "Just now" : "Ready"}</small><ChevronRight size={13}/></p>)}</div></div>;
}
function AnalyticsSurface() { return <div className="feature-page"><p className="feature-intro">Understand visits and usage across your published project.</p><div className="metrics-row">{[["Unique visitors","1,420"],["Pageviews","5,890"],["Avg. session","2m 45s"]].map(([label,value]) => <article key={label}><small>{label}</small><b>{value}</b><em>+12% this week</em></article>)}</div><div className="analytics-card"><div><b>Visitors</b><span>Last 7 days</span></div><div className="bar-chart">{[38,52,44,68,58,81,92].map((height,index) => <i key={index} style={{ height: `${height}%` }}/>)}</div></div></div>; }
function SecuritySurface() { return <div className="feature-page"><div className="security-summary"><ShieldCheck size={25}/><div><b>No critical findings</b><p>Your project passed its latest security review.</p></div><Button variant="editorActive" size="sm">Run scan</Button></div><div className="finding-row"><span>MEDIUM</span><div><b>Review content security policy</b><p>Restrict external media sources before publishing.</p></div><Button variant="outline" size="sm">Fix with Lovable</Button></div></div>; }
function FeatureSurface({ surface }: { surface: Surface }) { const data = useMemo(() => ({ ai: ["AI usage", "Monitor models, request volume, and spend.", Sparkles], agents: ["Agent integrations", "Connect tools that extend your project agent.", Sparkles], payments: ["Payments", "Set up products, subscriptions, and checkout.", CreditCard], seo: ["SEO & AI search", "Review metadata, indexing, and accessibility.", Globe2], logs: ["Logs", "Inspect recent project activity.", Terminal] } as const), []); const item = data[surface as keyof typeof data] ?? ["Project tool", "Configure this project feature.", Settings] as const; const Icon = item[2]; if (surface === "connectors") return <FirecrawlSurface/>; return <div className="feature-page"><div className="feature-empty"><span><Icon size={21}/></span><h3>{item[0]}</h3><p>{item[1]}</p><Button variant="editorActive" size="sm">Open setup</Button></div></div>; }

function FirecrawlSurface() {
  const [connected, setConnected] = useState(false);
  const [url, setUrl] = useState("https://");
  const [crawling, setCrawling] = useState(false);
  const [lastResult, setLastResult] = useState("No crawl started yet");
  const startCrawl = () => { if (!url.replace("https://", "").trim() || crawling) return; setCrawling(true); window.setTimeout(() => { setCrawling(false); setLastResult("12 pages extracted · Markdown ready"); }, 800); };
  return <div className="feature-page connector-page"><div className="connector-hero"><div className="connector-icon firecrawl-icon"><Flame size={20}/></div><div><div className="feature-kicker">CONNECTOR <span className="connector-live">{connected ? "Connected" : "Not connected"}</span></div><h3>Firecrawl</h3><p>Turn websites into clean, agent-ready content for your project.</p></div><Button variant={connected ? "outline" : "editorActive"} size="sm" onClick={() => setConnected((value) => !value)}>{connected ? "Disconnect" : "Connect"}</Button></div><div className="connector-grid"><section className="connector-card"><div className="connector-card-head"><span><KeyRound size={15}/><b>API connection</b></span><span className={connected ? "status-good" : "status-muted"}>{connected ? "Ready" : "Needs setup"}</span></div><p>Use Firecrawl for crawl, scrape, and map actions from the agent.</p><label className="settings-field">API key<input type="password" placeholder={connected ? "••••••••••••••••" : "fc-..."}/></label><Button variant="outline" size="sm" onClick={() => setConnected(true)}><Check size={13}/> Save connection</Button></section><section className="connector-card"><div className="connector-card-head"><span><Globe2 size={15}/><b>Quick crawl</b></span><span className="status-muted">{lastResult}</span></div><p>Capture a site map and readable Markdown in one pass.</p><label className="settings-field">Website URL<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com"/></label><div className="crawl-row"><Button variant="editorActive" size="sm" onClick={startCrawl}>{crawling ? "Crawling…" : "Start crawl"}</Button><Button variant="ghost" size="sm"><Settings size={13}/> Options</Button></div></section></div><div className="crawl-presets"><span><Activity size={14}/> 500 pages / month</span><span><CheckCircle2 size={14}/> Markdown extraction</span><span><ShieldCheck size={14}/> Private project data</span></div></div>;
}
